version: '2'
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-server -bootstrap -ui-dir /ui"
  registrator:
    image: "gliderlabs/registrator:latest"
    container_name: "registrator"
    depends_on:
      - consul
    command: "consul://consul1:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  database:
    image: "mysql"
    container_name: "mysql"
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    depends_on:
      - registrator
  web:
    build:
      context: .
#      args:
#        HTTP_PROXY: "http://172.16.154.10:3128" 
#        HTTPS_PROXY: "http://172.16.154.10:3128"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - registrator
